#!/bin/bash
# Just the update portion
source "$(dirname "$0")"/backups2datalad-cron-common

eval python -m tools.backups2datalad \
   -l WARNING \
   --backup-root "$backup_root" \
   --config tools/backups2datalad.cfg.yaml \
   update-from-backup \
   '000026' '000108' '000243'
