#!/bin/bash
source "$(dirname "$0")"/backups2datalad-cron-common

backups2datalad \
   -l DEBUG \
   --backup-root "$backup_root" \
   --config tools/backups2datalad.cfg.yaml \
   populate "$@" 2>|.git/tmp/stderr-pa

if [ -s .git/tmp/stderr-pa ]; then
	echo "There was stderr from backup/datalad invocations:"
	cat .git/tmp/stderr-pa
fi
