#!/bin/bash
set -eu

export PS1='$ '
PS4='> '
#set -x

ds="$(realpath "$(dirname "$0")"/..)"
backup_root="$(dirname "$ds")"

source ~/.bashrc-miniconda
conda activate dandisets-2

cd "$ds"
chronic pip install git+https://github.com/dandi/backups2datalad

: "${DATALAD_LOG_LEVEL:=WARNING}"  # otherwise too much noise
export DATALAD_LOG_LEVEL

mkdir -p .git/tmp

set -x -o pipefail
