#!/bin/bash

set -eu

export PS1='$ '
PS4='> '
#set -x

girderdir=/mnt/backup/dandi/dandiarchive-s3-backup/ 
ds=$(dirname "$0")
ds=$(dirname "$ds")

source ~/.bashrc-miniconda
conda activate dandisets

cd "$ds"
export DATALAD_LOG_LEVEL=WARNING  # otherwise too much of noise

set -x
eval tools/backups2datalad.py \
   --backup-remote dandi-dandisets-dropbox  \
   --gh-org dandisets \
   -l WARNING \
   -J 5 \
   "$girderdir" \
   "$ds" \
   "$*"
# TODO - save only the ones which were updated
#  probably should be done by backups2datalad.py itself!
datalad save -m "CRON update" -d . 00*
datalad push -J 5

# we must be clean
git diff --exit-code 
