#!/bin/bash
# Just the update portion
source "$(dirname "$0")"/backups2datalad-cron-common

(
# 001411 and 000571 - also temp failing, zarrbargo and large .dandi/assets.json - fixing
backups2datalad \
   -l WARNING \
   --backup-root "$backup_root" \
   --config tools/backups2datalad.cfg.yaml \
   update-from-backup \
   --workers 5 \
   -e '00(0(026|108|243|719)|1412|1461|1411|0571)$' \
   "$@" 2>&1 | grep -v 'nothing to save, working tree clean'

git pull --commit --no-edit
datalad push -J 5
) 2>|.git/tmp/stderr-2

if [ -s .git/tmp/stderr-2 ]; then
	echo "There was stderr from backup/datalad invocations:"
	cat .git/tmp/stderr-2
fi

# we must be clean
# TODO: disable temporarily since 000108 is problematic
# git diff --exit-code
