#!/bin/bash
set -eu

export PS1='$ '
PS4='> '
#set -x

ds="$(realpath "$(dirname "$0")"/..)"
backup_root="$(dirname "$ds")"
venv_path="$ds"/venv

if ! test -d "$venv_path"
then python3 -m venv "$venv_path"
fi
. "$venv_path"/bin/activate

if pip show backups2datalad >/dev/null 2>&1
then
    # Uninstall backups2datalad so that the subsequent `pip install` will
    # always install the latest code
    chronic pip uninstall --yes backups2datalad
fi
chronic pip install --upgrade-strategy eager git+https://github.com/dandi/backups2datalad

: "${DATALAD_LOG_LEVEL:=WARNING}"  # otherwise too much noise
export DATALAD_LOG_LEVEL

cd "$ds"

mkdir -p .git/tmp

source .git/secrets

set -x -o pipefail
