#!/bin/bash
# Just the update portion
# TODO: absorb common functionality into a reusable component

set -eu

export PS1='$ '
PS4='> '
#set -x

ds=$(dirname "$0")
ds=$(dirname "$ds")

zarrds=/mnt/backup/dandi/dandizarrs

source ~/.bashrc-miniconda
conda activate dandisets

cd "$ds"
chronic pip install -r tools/backups2datalad.req.txt

export DATALAD_LOG_LEVEL=WARNING  # otherwise too much of noise

mkdir -p .git/tmp

set -o pipefail
set -x

(
eval python -m tools.backups2datalad \
   -l WARNING \
   -J 5 \
   --target "$ds" \
   update-from-backup \
   --zarr-target "$zarrds" \
   --backup-remote dandi-dandisets-dropbox  \
   --zarr-backup-remote dandi-dandizarrs-dropbox  \
   --gh-org dandisets \
   --zarr-gh-org dandizarrs \
   -e '000108$' \
   "$*" 2>&1 | grep -v 'nothing to save, working tree clean'

git pull  
datalad push -J 5
) 2>|.git/tmp/stderr-2

if [ -s .git/tmp/stderr-2 ]; then
	echo "There was stderr from backup/datalad invocations:"
	cat .git/tmp/stderr-2
fi

# we must be clean
# TODO: disable temporarily since 000108 is problematic
# git diff --exit-code
