#!/bin/bash

set -eu

export PS1='$ '
PS4='> '
#set -x

girderdir=/mnt/backup/dandi/dandiarchive-s3-backup/ 
ds=$(dirname "$0")
ds=$(dirname "$ds")

source ~/.bashrc-miniconda
conda activate dandisets

cd "$ds"
eval tools/backups2datalad.py \
   --backup-remote dandi-dandisets-dropbox  \
   --gh-org dandisets \
   -J 5 \
   -e '000003$' \
   "$girderdir" \
   "$ds" \
   "$*"
# TODO - save only the ones which were updated
#  probably should be done by backups2datalad.py itself!
# TEMP: disable since 00003 needs fixing
#datalad save -m "CRON update" -d . 00*
#datalad push -J 5

# we must be clean
git diff --exit-code 
