#!/bin/bash
source "$(dirname "$0")"/backups2datalad-cron-common

python -m tools.backups2datalad \
   -l DEBUG \
   --backup-root "$backup_root" \
   --config tools/backups2datalad.cfg.yaml \
   populate-zarrs "$@" 2>|.git/tmp/stderr-pz

if [ -s .git/tmp/stderr-pz ]; then
	echo "There was stderr from backup/datalad invocations:"
	cat .git/tmp/stderr-pz
fi
