#!/bin/bash
source "$(dirname "$0")"/backups2datalad-cron-common

(
python -m tools.backups2datalad \
   -l DEBUG \
   --backup-root "$backup_root" \
   --config tools/backups2datalad.cfg.yaml \
   populate "$@"

datalad foreach-dataset -s -r -R 1 -J 5 --chpwd pwd --cmd-type eval 'ds.push(to="github")'

) 2>|.git/tmp/stderr-pa

if [ -s .git/tmp/stderr-pa ]; then
	echo "There was stderr from backup/datalad invocations:"
	cat .git/tmp/stderr-pa
fi
