#!/bin/bash

set -eu

export PS1='$ '
PS4='> '
#set -x

ds=$(dirname "$0")
ds=$(dirname "$ds")

source ~/.bashrc-miniconda
conda activate dandisets

cd "$ds"
chronic pip install -r tools/backups2datalad.req.txt

export DATALAD_LOG_LEVEL=WARNING  # otherwise too much of noise

mkdir -p .git/tmp

set -o pipefail
set -x

(
python -m tools.backups2datalad \
   -l DEBUG \
   -J 5 \
   --backup-root "$ds" \
   --config tools/backups2datalad.cfg.yaml \
   populate "$@"

datalad foreach-dataset -s -r -R 1 -J 5 --chpwd pwd --cmd-type eval 'ds.push(to="github")'

) 2>|.git/tmp/stderr-pa

if [ -s .git/tmp/stderr-pa ]; then
	echo "There was stderr from backup/datalad invocations:"
	cat .git/tmp/stderr-pa
fi
