#!/bin/bash
source "$(dirname "$0")"/backups2datalad-cron-common

backups2datalad \
    -l WARNING \
    --backup-root "$backup_root" \
    --config tools/backups2datalad.cfg.yaml \
    backup-zarrs \
    --workers 10 \
    --partial-dir /mnt/fast/dandi/partial-zarrs \
    '000108' |& tee .git/tmp/update-zarrs-"$(date -u +%Y.%m.%d.%H.%M.%S)".log
