name: Test

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
        noxenv: [test]
        include:
          - python-version: '3.8'
            noxenv: typing
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade --upgrade-strategy=eager nox

      - name: Run tests
        run: nox -e ${{ matrix.noxenv }}
        working-directory: tools

# vim:set et sts=2:
