name: Test

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * 0'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version:
        #  - '3.10'
        #  - '3.11'
        #noxenv: [test]
        include:
          - python-version: '3.10'
            noxenv: typing
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade --upgrade-strategy=eager nox

      - name: Run tests with coverage
        if: matrix.noxenv == 'test'
        run: nox -e test -- --cov-report=xml
        working-directory: tools
        env:
          DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}

      - name: Run generic tests
        if: matrix.noxenv != 'test'
        run: nox -e ${{ matrix.noxenv }}
        working-directory: tools

      - name: Upload coverage to Codecov
        if: matrix.noxenv == 'test'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          files: tools/coverage.xml

# vim:set et sts=2:
